Story4/Story4/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('gallery/', views.gallery, name='gallery'),
    path('friendform/', views.friendform, name='friendform'),
    path('friendlist/', views.friendlist, name='friendlist'),
    path('thanks/', views.thanks, name='thanks'),
]

homepage/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

# Create your models here.

class Year(models.Model):
    year = models.CharField(max_length=6,primary_key=True)

    def __str__(self):
        return '%s' % self.year

class Data(models.Model):
    name = models.CharField(primary_key=True, max_length=30)
    hobby = models.CharField(max_length=30)
    your_year = models.ForeignKey(Year, on_delete=models.CASCADE)
    fnb = models.CharField(max_length=30)

    def __str__(self):
        return '%s' % self.name

homepage/forms.py
from django.forms import ModelForm
from .models import Data, Year

class DataForm(ModelForm):
    class Meta:
        model = Data
        fields = '__all__'

homepage/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import DataForm
from .models import Data

# Create your views here.

def home(request):
    return render(request, 'homepage/home.html')

def about(request):
    return render(request, 'homepage/about.html')

def contact(request):
    return render(request, 'homepage/contact.html')

def gallery(request):
    return render(request, 'homepage/gallery.html')

def friendform(request):
    if request.method == 'POST':
        form = DataForm(request.POST)
        if form.is_valid():
            data_item = form.save(commit=False)
            data_item.save()
            return render(request, 'homepage/thanks.html')
    else:
        form = DataForm()
        return render(request, 'homepage/friendform.html', {'form' : form})

def friendlist(request):
    allfriends = Data.objects.all()
    return render(request, 'homepage/friendlist.html', {'allfriends':allfriends})

def thanks(request):
    return render(request, 'homepage/thanks.html')

homepage/templates/homepage/about.html
{% extends "homepage/base.html" %}
{% load static %}
	{% block content %}
		
		<title>Get to Know Me!</title>
		
	</head>

	<body class="body">

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top" id="mainNav">
			<div class="container">
				<a class="navfont" style="color:white">BAGUS PRABOWO</a>
				<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:home' %}">HOME</a>
						</li>
						<li class="nav-item active">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:about' %}">ABOUT</a>
						</li>
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:contact' %}">CONTACT ME</a>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle navfont" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							  FORM
							</a>
							<div class="dropdown-menu bg-dark navfont" aria-labelledby="navbarDropdown">
							  <a class="dropdown-item" style="color:white !important" href="{%  url 'homepage:friendform' %}">FORM FILL</a>
							  <div class="dropdown-divider"></div>
							  <a class="dropdown-item" style="color:white !important;" href="{%  url 'homepage:friendlist' %}">FRIENDS LIST</a>
							</div>
						</li>
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:gallery' %}">GALLERY</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		
		<div class="container">
			
			<div class="col-md-auto welcome">
				<b>
					ABOUT ME
				</b>
			</div>
			
		</div>
			
			
		<div class="container" style="margin-bottom:25px">
			
			<div class="row justify-content-start center">
				<div class="col-md-auto col-sm text-center">
					<img src="{% static 'homepage/Pictures/lab315345.jpeg' %}" alt="Bagus 1" class="profilepicture picturemargin" data-aos="fade" data-aos-duration="2000">
				</div>
				<div class="col-sm bodyfont about1">
					Hi! I'm Bagus. I'm a second semester Computer Science student in The University of Indonesia class of 2019.
				</div>
			</div>
			
			<div class="row justify-content-around center margintop">
				<div class="col-sm bodyfont about2">
					I'm interested in cooking and photography, especially film photography. Everything in this website are captured using C-41 films.
				</div>
				<div class="col-sm col-md-auto text-center">
					<img src="{% static 'homepage/Pictures/lab315317.jpeg' %}" alt="Bagus 2" class="profilepicture picturemargin" data-aos="fade-up" data-aos-duration="2000">
				</div>
			</div>
			
			<div class="row justify-content-end center margintop">
				<div class="col-sm col-md-auto text-center">
					<img src="{% static 'homepage/Pictures/lab315302.jpeg' %}" alt="Rustic Egypt" class="profilepicture picturemargin" data-aos="fade-right" data-aos-duration="2000">
				</div>
				<div class="col-sm text-center bodyfont">
					As for my skills, I can do the basics of programming in Python Programming Language. Currently studying Java, HTML5, CSS, and JavaScript.
					<br><br>
					<button type="button" class="btn btn-primary shadow-none bg-brown" data-toggle="modal" data-target="#exampleModal">
						<b class="bodyfont"><u>Click Here for my CV</u></b>
					</button>

					</a>
				</div>
			</div>
			
		</div>

		<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title buttonfont" id="exampleModalLabel" style="color:black">See my education and experience history!</b></h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					
					<div class="modal-body buttonfont" style="color:black; font-size:125%">
						Click below to download my CV!
					</div>
					
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary navfont" data-dismiss="modal" style="background:black; font-size:100%">Close</button>
						<a href="{% static 'homepage/CV.pdf' %}">
							<button type="button" class="btn btn-secondary navfont" style="background:black; font-size:100%">Download my CV</button>
						</a>
					</div>
				</div>
			</div>
		</div>
	
{% endblock %}

homepage/templates/homepage/base.html
<!doctype html>
{% load static %}
<html lang="en">

	<head>
		
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		
		<link rel="stylesheet" type="text/css" href="{% static 'homepage/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'homepage/style.css' %}">
		<link href="https://fonts.googleapis.com/css?family=Bebas+Neue|Playfair+Display&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="https://unpkg.com/aos@next/dist/aos.css">
        
        {% block content %}{% endblock %}
    
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
		<script type="text/javascript" src="{% static 'homepage/js/bootstrap.min.js' %}"></script>
		<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
		<script>
		  AOS.init();
		</script>
	</body>
	
</html>

homepage/templates/homepage/contact.html
{% extends "homepage/base.html" %}
{% load static %}

	{% block content %}
		
		<title>Contact List</title>
		
	</head>

	<body class="body">

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top" id="mainNav">
			<div class="container">
				<a class="navfont" style="color:white">BAGUS PRABOWO</a>
				<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:home' %}">HOME</a>
						</li>
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:about' %}">ABOUT</a>
						</li>
						<li class="nav-item active">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:contact' %}">CONTACT ME</a>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle navfont" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							  FORM
							</a>
							<div class="dropdown-menu bg-dark navfont" aria-labelledby="navbarDropdown">
							  <a class="dropdown-item" style="color:white !important" href="{%  url 'homepage:friendform' %}">FORM FILL</a>
							  <div class="dropdown-divider"></div>
							  <a class="dropdown-item" style="color:white !important;" href="{%  url 'homepage:friendlist' %}">FRIENDS LIST</a>
							</div>
						</li>
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:gallery' %}">GALLERY</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		
		<div class="container center">
			
			<div class="col-md-auto welcome">
				<b>
					GET IN TOUCH WITH ME!
				</b>
			</div>
			
		</div>
			
		<div class="container" style="margin-top:50px; margin-bottom:100px">	
		
		
			<div class="card-deck">
			
			
				<div class="card" data-aos="fade-left" data-aos-duration="2000">
					<div class="card-body center">
						<h5 class="card-title cardtitlefont">INSTAGRAM</h5>
						<p class="card-text cardfont">Follow me to see more of my film photography madness!</p>
						<a href="http://www.instagram.com/prbagus">
							<button type="button" class="btn btn-primary navfont bg-dark shadow-none" data-toggle="button" aria-pressed="false" style="font-size:150%">
								@prbagus
							</button>
						</a>
					</div>
				</div>
				
				<div class="card" style="background-color:black" data-aos="fade-right" data-aos-duration="2000">
					<div class="card-body" style="color:white">
						<h5 class="card-title cardtitlefont" style="color:white">LINKEDIN</h5>
						<p class="card-text cardfont">Check me out on LinkedIn for more education and experience information.</p>
						<a href="https://www.linkedin.com/in/bagus-prabowo-reksoprodjo-55152619b/">
							<button type="button" class="btn btn-primary navfont bg-white shadow-none" style="color:black; margin-bottom:5px" data-toggle="button" aria-pressed="false" style="font-size:150%">
								BAGUS' LINKEDIN
							</button>
						</a>
					</div>
				</div>
				
				<div class="card" data-aos="fade-left" data-aos-duration="2000">
					<div class="card-body">
						<h5 class="card-title cardtitlefont">E-MAIL</h5>
						<p class="card-text cardfont">Or, send an email to me!<br>I'll try to reply as fast as I can.</p>
						<a href="mailto:bagus3621@gmail.com">
							<button type="button" class="btn btn-primary navfont bg-dark shadow-none" data-toggle="button" aria-pressed="false" style="font-size:150%; margin-top:20px">
								BAGUS' GMAIL
							</button>
						</a>
					</div>
				</div>
				
				
			</div>	
			
		</div>
		
{% endblock %}

homepage/templates/homepage/friendform.html
{% extends "homepage/base.html" %}
{% load static %}

	{% block content %}
		
		<title>Form List</title>
		
    </head>

    <body class="body">

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top" id="mainNav">
			<div class="container">
				<a class="navfont" style="color:white">BAGUS PRABOWO</a>
				<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:home' %}">HOME</a>
						</li>
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:about' %}">ABOUT</a>
						</li>
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:contact' %}">CONTACT ME</a>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle navfont" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							  FORM
							</a>
							<div class="dropdown-menu bg-dark navfont" aria-labelledby="navbarDropdown">
							  <a class="dropdown-item" style="color:white !important" href="{%  url 'homepage:friendform' %}">FORM FILL</a>
							  <div class="dropdown-divider"></div>
							  <a class="dropdown-item" style="color:white !important;" href="{%  url 'homepage:friendlist' %}">FRIENDS LIST</a>
							</div>
						</li>
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:gallery' %}">GALLERY</a>
						</li>
					</ul>
				</div>
			</div>
        </nav>
        
        <div class="container center">
			
			<div class="col-md-auto welcome">
				<b>
					FEEL FREE TO FILL THIS FORM!
				</b>
            </div>

            <div class="row justify-content-start center">
                <div class="col-sm bodyfont about1">
                    Fill this form so that I would know that you have visited my page!
                </div>
            </div>
			
			<div class="col-md-auto col-sm text-center">
				<form method="POST" action="">
					{%  csrf_token %}
					<ul class = "navfont" style = "list-style-type:none; color:black">
						<li id="Name">NAME<br>{{ form.name }}</li>
						<li id="Year">YEAR<br>{{ form.your_year }}</li>
						<li id="Hobby">HOBBY<br>{{ form.hobby }}</li>
						<li id="Food and Beverages">FAVOURITE FOOD OR DRINKS<br>{{ form.fnb }}</li>
						<li id="Submit">
							<button type="submit" class="btn btn-primary navfont bg-dark shadow-none  submit" data-toggle="button" aria-pressed="false" value="submit">
								SUBMIT
							</button>
						</li>
					</ul>
				</form>
			</div>

		</div>

    </body>


{% endblock %}

homepage/templates/homepage/friendlist.html
{% extends "homepage/base.html" %}
{% load static %}

	{% block content %}
		
		<title>Friends List</title>
		
    </head>

    <body class="body">

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top" id="mainNav">
			<div class="container">
				<a class="navfont" style="color:white">BAGUS PRABOWO</a>
				<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:home' %}">HOME</a>
						</li>
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:about' %}">ABOUT</a>
						</li>
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:contact' %}">CONTACT ME</a>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle navfont" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							  FORM
							</a>
							<div class="dropdown-menu bg-dark navfont" aria-labelledby="navbarDropdown">
							  <a class="dropdown-item" style="color:white !important" href="{%  url 'homepage:friendform' %}">FORM FILL</a>
							  <div class="dropdown-divider"></div>
							  <a class="dropdown-item" style="color:white !important;" href="{%  url 'homepage:friendlist' %}">FRIENDS LIST</a>
							</div>
						</li>
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:gallery' %}">GALLERY</a>
						</li>
					</ul>
				</div>
			</div>
        </nav>


        <div class="container">
		<div class="row">
			{% for Data in allfriends %}
			<div class="col-sm-6 col-md-auto" style = "margin-top: 20px;">
				<div class="card">
				  <div class="card-body">
					<h5 class="card-title">{{ Data.name }}</h5>
					<h6 class="card-subtitle mb-2 text-muted">Details</h6>
					<p class="card-text">Year: {{ Data.your_year }}</p>
					<p class="card-text">Hobby: {{ Data.hobby }}</p>
					<p class="card-text">Fav. F&B: {{ Data.fnb }}</p>
				  </div>
				</div>
			  </div>
			  {% endfor %}
			</div>
        </div>
		
		
		{% endblock %}

homepage/templates/homepage/gallery.html
{% extends "homepage/base.html" %}
{% load static %}

	{% block content %}
		
		<title>Gallery</title>
		
	</head>

	<body class="body">

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top" id="mainNav">
			<div class="container">
				<a class="navfont" style="color:white">BAGUS PRABOWO</a>
				<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:home' %}">HOME</a>
						</li>
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:about' %}">ABOUT</a>
						</li>
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:contact' %}">CONTACT ME</a>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle navfont" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							  FORM
							</a>
							<div class="dropdown-menu bg-dark navfont" aria-labelledby="navbarDropdown">
							  <a class="dropdown-item" style="color:white !important" href="{%  url 'homepage:friendform' %}">FORM FILL</a>
							  <div class="dropdown-divider"></div>
							  <a class="dropdown-item" style="color:white !important;" href="{%  url 'homepage:friendlist' %}">FRIENDS LIST</a>
							</div>
						</li>
						<li class="nav-item active">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:gallery' %}">GALLERY</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	
		<div class="container center">
			
			<div class="col-md-auto welcome">
				<b>
					SEE MORE OF MY WORK
				</b>
			</div>
			
		</div>
		
		<div class="container" style="margin-top:50px; margin-bottom:50px" data-aos="fade" data-aos-duration="2000">
		
			<div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
			
				<div class="carousel-inner galleryborder" style="margin:0 auto">
				
					<div class="carousel-item active">
						<img src="/static/homepage/Pictures/lab315351.jpeg" class="d-block w-100 picture" alt="Jordan">
					</div>
					
					<div class="carousel-item">
						<img src="/static/homepage/Pictures/IMG-4983.jpeg" class="d-block w-100 picture" alt="Jordan">
					</div>
					
					<div class="carousel-item">
						<img src="/static/homepage/Pictures/c417597.jpeg" class="d-block w-100 picture" alt="Jordan">
					</div>
					
					<div class="carousel-item">
						<img src="/static/homepage/Pictures/c417596.jpeg" class="d-block w-100 picture" alt="Jordan">
					</div>
					
					<div class="carousel-item">
						<img src="/static/homepage/Pictures/c417531.jpeg" class="d-block w-100 picture" alt="Jordan">
					</div>
					
				</div>

				
				<a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
					<span class="carousel-control-prev-icon" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				
				<a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
				
			</div>
			
			
		</div>
	
{% endblock %}

homepage/templates/homepage/home.html
{% extends "homepage/base.html" %}
{% load static %}
	{% block content %}
		
		<title>Welcome</title>
		
	</head>

	<body class="body">

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top" id="mainNav">
			<div class="container">
				<a class="navfont" style="color:white">BAGUS PRABOWO</a>
				<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item active">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:home' %}">HOME</a>
						</li>
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:about' %}">ABOUT</a>
						</li>
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:contact' %}">CONTACT ME</a>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle navfont" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							  FORM
							</a>
							<div class="dropdown-menu bg-dark navfont" aria-labelledby="navbarDropdown">
							  <a class="dropdown-item" style="color:white !important" href="{%  url 'homepage:friendform' %}">FORM FILL</a>
							  <div class="dropdown-divider"></div>
							  <a class="dropdown-item" style="color:white !important;" href="{%  url 'homepage:friendlist' %}">FRIENDS LIST</a>
							</div>
						</li>
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:gallery' %}">GALLERY</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		
		<div class="container" style="margin-top:25px">
		
			<div class="row center welcomemargin">
				<div class="col-md-auto text-center col-sm picture1">
					<img src="{% static 'homepage/Pictures/c2632.jpeg' %}" class="nongallery" alt="Volendam" data-aos="fade" data-aos-duration="2000">
				</div>
				<div class="col-6 col-md-4 text-center col-sm">
					<p class="dropdown welcome" style="line-height:1.2">
						Welcome<br>To<br>My<br>Page<br>
					</p>
				</div>
			</div>
				
			<div class="row justify-content-between">
				<div class="col-sm welcome get">
					Get To<br>Know Me More!
					<img src="{% static 'homepage/Pictures/c2599.jpeg' %}" alt="Forest" class="nongallery" data-aos="fade-left" data-aos-duration="2000" style="margin-top:50px">
				</div>
				<div class="col-sm">
					<img src="{% static 'homepage/Pictures/c2631.jpeg' %}" alt="Volendam 2" class="nongallery" data-aos="fade-right" data-aos-duration="2000" style="margin-top:50px">
				</div>
			</div>
			
			<div class="row justify-content-around" style="margin-top:0px; margin-bottom:0px">
				<div class="col-sm">
					<a href="{% url 'homepage:about' %}">
						<button type="button" class="btn btn-primary navfont bg-dark shadow-none learn" data-toggle="button" aria-pressed="false">
							Learn More
						</button>
					</a>
				</div>
				<div class="col-sm text-center">
					<img src="{% static 'homepage/Pictures/IMG-4998.jpeg' %}" alt="Restaurant" class="nongallery" data-aos="fade-down" data-aos-duration="2000" style="margin-bottom:20px">
				</div>
			</div>
			
		</div>
	
{% endblock %}

homepage/templates/homepage/thanks.html
{% extends "homepage/base.html" %}
{% load static %}

	{% block content %}
		
		<title>Thanks</title>
		
    </head>

    <body class="body">

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top" id="mainNav">
			<div class="container">
				<a class="navfont" style="color:white">BAGUS PRABOWO</a>
				<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:home' %}">HOME</a>
						</li>
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:about' %}">ABOUT</a>
						</li>
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:contact' %}">CONTACT ME</a>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle navfont" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							  FORM
							</a>
							<div class="dropdown-menu bg-dark navfont" aria-labelledby="navbarDropdown">
							  <a class="dropdown-item" style="color:white !important" href="{%  url 'homepage:friendform' %}">FORM FILL</a>
							  <div class="dropdown-divider"></div>
							  <a class="dropdown-item" style="color:white !important;" href="{%  url 'homepage:friendlist' %}">FRIENDS LIST</a>
							</div>
						</li>
						<li class="nav-item">
							<a class="nav-link js-scroll-trigger navfont" href="{% url 'homepage:gallery' %}">GALLERY</a>
						</li>
					</ul>
				</div>
			</div>
        </nav>


        <div class="row justify-content-start center">
            <div class="col-sm bodyfont about1" style="margin-top:50px; font-size:300%">
                Thank you for your submission!
            </div>
        </div>
		
		
		{% endblock %}